# Generated by Django 5.0 on 2024-02-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTable',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'gaz_reports',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', models.CharField(max_length=100)),
                ('card_id', models.BigIntegerField()),
                ('date', models.DateField()),
                ('matched', models.CharField(choices=[('совпадает', 'совпадает'), ('Расходится', 'Расходится'), ('запись отсутсвует в транзакциях', 'запись отсутсвует в транзакциях'), ('запись отсутсвует в ЗВ', 'запись отсутсвует в ЗВ')], null=True)),
                ('variance', models.FloatField()),
                ('created_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaz.resulttable')),
            ],
            options={
                'db_table': 'gaz_result',
            },
        ),
    ]
