# Generated by Django 5.0 on 2024-03-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaz', '0003_alter_result_options_alter_result_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttable',
            name='all_rows',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='matched_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='other_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='unmathed_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
